#!/bin/sh

rm -rvf ../.config
mkdir -v ../.config
    
cp -rv ~/.config/autoclicker    ../.config
cp -rv ~/.config/swww           ../.config
cp -rv ~/.config/hypr           ../.config
cp -rv ~/.config/waybar         ../.config
cp -rv ~/.config/alacritty      ../.config
cp -rv ~/.config/i3blocks       ../.config
cp -rv ~/.config/neofetch       ../.config
cp -rv ~/.config/dunst          ../.config
cp -rv ~/.config/polybar        ../.config
cp -rv ~/.config/picom          ../.config
cp -rv ~/.config/kitty          ../.config
cp -rv ~/.config/cava           ../.config
cp -rv ~/.config/rofi           ../.config
cp -rv ~/.config/i3             ../.config
cp -rv ~/.xinitrc               ..
cp -rv ~/.Xmodmap               ..
cp -rv ~/.bashrc                ..
cp -rv ~/.tmux.conf             ..
# nice
