#!/bin/bash
case $BLOCK_BUTTON in
    # Clicking will mute
    1) amixer -q sset Master Playback toggle && FORMAT=1 ;;
    2) amixer -q sset Master Playback toggle && FORMAT=1 ;;
    3) amixer -q sset Master Playback toggle && FORMAT=1 ;;

    # Scrolling up and down will increase/decrease
    4) amixer -q sset Master Playback 5%+ unmute && FORMAT=1 ;;
    5) amixer -q sset Master Playback 5%- unmute && FORMAT=1 ;;
esac

STATUSLINE_DEF=$(amixer get Master | tail -n 1)
STATUS=$(echo "${STATUSLINE_DEF}" | grep -wo "on")
VOLUME=$(echo "${STATUSLINE_DEF}" | awk -F ' ' '{print $5}' | tr -d '[]%')

if [[ "${STATUS}" == "on" ]]; then
    echo "${VOLUME}%"
else
    echo "muted"
fi
