#!/bin/bash
WEATHER_TEMP=$(curl 'https://wttr.in/?format=%t')
WEATHER_ICON=$(curl 'https://wttr.in/?format=%c')
WEATHER_STAT=$(curl 'https://wttr.in/?format=%c')
WTH=$(curl wttr.in/?format\="%t%20|%20%h%20|%20%P%20|%20%w")
echo "${WTH}"

