#!/bin/bash 

# Get the window name
WINDOW_NAME=$(xdotool getactivewindow getwindowname)

# Check if the string is longer than 50 characters
if [ ${#WINDOW_NAME} -gt 46 ]; then
    # Cut it down to 50 characters and append "..."
    WINDOW_NAME=$(echo "$WINDOW_NAME" | cut -c 1-46)"..."
fi

# Display the modified window name
echo "$WINDOW_NAME"

