#!/bin/sh

dir="${HOME}/.config/swww/walls"
BG="$(find "$dir" -name '*.jpg' -o -name '*.png' | shuf -n1)"

# Check if the program is running
if pgrep "swww-deamon" >/dev/null; then
	swww init
fi

swww img "$BG" \
    --transition-type grow \
    --transition-pos "$(hyprctl cursorpos)" \
    --invert-y \
    --transition-fps 144 \
    --transition-step 255 
