#!/bin/sh

dir="${HOME}/.config/swww/walls"
BG="$(find "$dir" -name '*.jpg' -o -name '*.png' | shuf -n1)"

# Check if the program is running
if pgrep "swww-deamon" >/dev/null; then
	swww init
fi

swww img "$BG" \
    --transition-type wipe \
    --transition-pos "$(hyprctl cursorpos)" \
    --invert-y \
    --transition-fps 60 \
    --transition-angle 30 \
    --transition-step 90

### transitions:
#"none"
#"simple"
#"left"
#"right"
#"top"
#"bottom"
#"wipe"
#"grow"
#"center"
#"outer"
#"any"
#"wave"
#"random"
#"fade"
